apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: go-programs-
spec:
  serviceAccountName: argo-workflow
  arguments:
    parameters:
      - name: target
        value: "hello2-step"
  entrypoint: dag-workflow
  templates:
    - name: dag-workflow
      dag:
        tasks:
          - name: hello1-step
            template: hello1-step
          - name: hello2-step
            template: hello2-step

    - name: hello1-step
      container:
        image: ghcr.io/s-quatres/go-wf-steps:latest
        env:
          - name: GO_RUN
            value: "hello1"

    - name: hello2-step
      container:
        image: ghcr.io/s-quatres/go-wf-steps:latest
        env:
          - name: GO_RUN
            value: "hello2"
      when: "{{workflow.parameters.target}} == hello2-step"

    - name: hello3-step
      container:
        image: ghcr.io/s-quatres/go-wf-steps:latest
        env:
          - name: GO_RUN
            value: "hello3"
      when: "{{workflow.parameters.target}} == hello3-step"
