apiVersion: v1
kind: Namespace
metadata:
  name: boinc

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: boinc-server
  namespace: boinc
spec:
  serviceName: boinc-server
  replicas: 0
  selector:
    matchLabels:
      app: boinc-server
  template:
    metadata:
      labels:
        app: boinc-server
    spec:
      containers:
        - name: boinc-server
          image: boinc/client:latest
          env:
            - name: BOINC_GUI_RPC_PASSWORD
              value: "123"
            - name: BOINC_CMD_LINE_OPTIONS
              value: "--allow_remote_gui_rpc"
          ports:
            - containerPort: 80
              name: http
            - containerPort: 31416
              name: rpc
          volumeMounts:
            - name: boinc-data
              mountPath: /var/lib/boinc
      volumes:
        - name: boinc-data
          persistentVolumeClaim:
            claimName: boinc-pvc
  volumeClaimTemplates:
    - metadata:
        name: boinc-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-path"
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: boinc-nodeport
  namespace: boinc
spec:
  type: NodePort
  selector:
    app: boinc-server
  ports:
    - protocol: TCP
      port: 31416
      targetPort: 31416
      nodePort: 31416
